### ISSUE TITLE
Array.indexOf() requires reference equality

### ISSUE THREAD

**Issue by tommyettinger** [earlygrey/simple-graphs#12]
I think this runs counter to one of the original goals of simple-graphs relative to gdx-ai, which would be to allow users to organize graphs in an intuitive way, instead of forcing reference equality like gdx-ai did at the time (and still does, as of the latest stable release).

The line in question is https://github.com/earlygrey/simple-graphs/blob/master/src/main/java/space/earlygrey/simplegraphs/Array.java#L91 . I haven't looked for other usage of reference equality. I could PR a fix, but I'm not sure what the desired behavior should be.

**Comment by earlygrey** [comment]
Nice catch - this is a mistake, it should check equals() not reference equality. The rest of the library considers vertex objects to be the same if they're equals(). This affects the returned paths you get via search algorithms.

If you have it ready you can PR a fix and I'll approve it, otherwise I'll make the change in the next few days.

**Comment by tommyettinger** [comment]
I PRed an initial, different commit that lets me build with my current JDK, but once that PR is accepted (or rejected, for some reason), I can PR this too.

**Comment by earlygrey** [comment]
Sorry for accepting the PR so late!
